name: Prueba

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v2

      - name: configura nodejs  
        uses: actions/setup-node@v2
        with:
            node-version: '16' 

      - name: Instalar Dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test